// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef DRIVEBASE_H
#define DRIVEBASE_H
#include <WPILib.h>
#include "../ThirdParty/NavX/include/AHRS.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveBase: public Subsystem {
private:
	std::shared_ptr<SpeedController> leftFront;
	std::shared_ptr<SpeedController> leftRear;
	std::shared_ptr<SpeedController> rightFront;
	std::shared_ptr<SpeedController> rightRear;
	std::shared_ptr<Encoder> leftEncoder;
	std::shared_ptr<Encoder> rightEncoder;
	std::shared_ptr<AHRS> navX;
public:
	DriveBase();
	void InitDefaultCommand();

	double ReadCurrentHeading();
	void ResetYaw();

	void SetLeftPower(double percent = 0);
	void SetRightPower(double percent = 0);

	double RightEncoderVelocity();
	double LeftEncoderVelocity();
	double RightEncoderDistance();
	double LeftEncoderDistance();
	uint32_t LeftEncoderRaw();
	uint32_t RightEncoderRaw();

	void RightEncoderReset();
	void LeftEncoderReset();
	void Stop();
};

#endif
