// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GYRO_H
#define GYRO_H

#include <WPILib.h>
#include <AHRS.h>


class Navigation: public Subsystem {
private:
	std::shared_ptr<AHRS> navX;

public:
	Navigation();
	void InitDefaultCommand();
	double ReadCurrentHeading();
	void Reset();
};

#endif
