// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Ramp.h"
#include "../RobotMap.h"
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Ramp::Ramp() : frc::Subsystem("Ramp") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    rightLinearActuatorServo = RobotMap::rampRightLinearActuatorServo;
    leftLinearActuatorServo = RobotMap::rampLeftLinearActuatorServo;
    leftRamp1 = RobotMap::rampLeftRamp1;
    leftRamp2 = RobotMap::rampLeftRamp2;
    rightRamp1 = RobotMap::rampRightRamp1;
    rightRamp2 = RobotMap::rampRightRamp2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Ramp::InitDefaultCommand(){

    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Ramp::Periodic() {
    // Put code here to be run every loop

}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Ramp::ExtendLeftRamp(){
	std::cerr << "Activating left ramp 1" << std::endl;
	leftRamp1->Set(frc::DoubleSolenoid::kForward);
	std::cerr << "Activating left ramp 2" << std::endl;
	leftRamp2->Set(frc::DoubleSolenoid::kForward);
}

void Ramp::ExtendRightRamp(){
	std::cerr << "Activating right ramp 1" << std::endl;
	rightRamp1->Set(frc::DoubleSolenoid::kForward);
	std::cerr << "Activating right ramp 2" << std::endl;
	rightRamp2->Set(frc::DoubleSolenoid::kForward);
}

void Ramp::Shutdown() {
	leftRamp1->Set(frc::DoubleSolenoid::kOff);
	leftRamp2->Set(frc::DoubleSolenoid::kOff);
	rightRamp1->Set(frc::DoubleSolenoid::kOff);
	rightRamp2->Set(frc::DoubleSolenoid::kOff);
}
