/*#include "Ramp.h"
#include "../RobotMap.h"

Ramp::Ramp() : frc::Subsystem("Ramp") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Left1Pneumatics = RobotMap::Left1Pneumatics;
    Left2Pneumatics = RobotMap::Left2Pneumatics;
    Right1Pneumatics = RobotMap::Right1Pneumatics;
    Right2Pneumatics = RobotMap::Right2Pneumatics;
}

void Ramp::InitDefaultCommand() {

}
void Ramp::(double percent){

}

void Ramp::(){

}

void Ramp::Stop(){

}
*/
