// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Pusher.h"
#include "Commands/Push.h"
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Pusher::Pusher() : frc::Subsystem("Pusher") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    pusher.reset(new frc::Servo(8));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // The .SetRawBounds() function should map  the .Set() function to the proper PWM values for the L16 Linear Actuator --Raymond
    // Max = 2000, min = 500, center = 1245 --Raymond

    //I also suggest setting the actuator to retract fully on construction --Raymond
}

void Pusher::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    SetDefaultCommand(new Push());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Pusher::Periodic() {
    // Put code here to be run every loop

}

double Pusher::GetPusherExtension() {
    return pusher->Get();
}

void Pusher::SetPusherExtension(double extension){
    const int position = scalePosition(extension);
    std::cout << "   Position = " << position
              << ", Extension = " << extension;
    pusher->SetRaw(position);
}
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.
