// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoScoreOnRightSwitchCommand.h"
#include "Primitives/MoveForDistance.h"
#include "Primitives/PointTurnLeft.h"
#include "Primitives/ShoulderMove.h"
#include "Primitives/Outtake.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoScoreOnRightSwitchCommand::AutoScoreOnRightSwitchCommand() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.

	AddSequential(new MoveForDistance(168, -.4));
	//14 feet
	AddSequential(new PointTurnLeft(90, .4));
	AddSequential(new MoveForDistance(22, .4));
//	AddSequential(new ShoulderMove(4, -.4));
//	AddSequential(new Outtake(4, .6));
	// I used 4 and .4 just to start may need to be adjusted

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
