


#include "AutoFMS.h"
AutoFMS::AutoFMS(): frc::Command() {

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


        // Use requires() here to declare subsystem dependencies
	Requires (Robot::driveBase.get());
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


void AutoFMS::Initialize() {
	std::string gameData;
	gameData = frc::DriverStation::GetInstance().GetGameSpecificMessage();
}


void AutoFMS::Execute() {


	}



bool AutoFMS::IsFinished() {
return false;
}


void AutoFMS::End() {


}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoFMS::Interrupted() {

}
