


#include "LimitIntake.h"

LimitIntake::LimitIntake(): frc::Command() {

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


        // Use requires() here to declare subsystem dependencies
	Requires (Robot::driveBase.get());
	Requires (Robot::limitSwitch.get());
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


void LimitIntake::Initialize() {

}


void LimitIntake::Execute() {


	}



bool LimitIntake::IsFinished() {
return false;
}


void LimitIntake::End() {


}


void LimitIntake::Interrupted() {

}
