// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "RobotMap.h"
#include <LiveWindow/LiveWindow.h>

std::shared_ptr<SpeedController> RobotMap::driveBaseLeftFrontMotor;
std::shared_ptr<SpeedController> RobotMap::driveBaseLeftRearMotor;
std::shared_ptr<SpeedController> RobotMap::driveBaseRightFrontMotor;
std::shared_ptr<SpeedController> RobotMap::driveBaseRightRearMotor;
std::shared_ptr<Joystick>        RobotMap::driverStick;
std::shared_ptr<Joystick>		 RobotMap::auxiliaryStick;

#ifdef USE_FRC_DRIVE_CODE
std::shared_ptr<RobotDrive> RobotMap::driveBaseRobotDrive21;
#endif	// USE_FRC_DRIVE_CODE

////////////////////////////////////////////////////////////////////////////////
// Hardware mappings

const int LEFT_FRONT_MOTOR_CHANNEL  = 0;
const int LEFT_REAR_MOTOR_CHANNEL   = 1;
const int RIGHT_FRONT_MOTOR_CHANNEL = 2;
const int RIGHT_REAR_MOTOR_CHANNEL  = 3;

const int DRIVER_JOYSTICK_PORT      = 0;
const int AUXILIARY_JOYSTICK_PORT   = 1;


void RobotMap::init() {
    LiveWindow *lw = LiveWindow::GetInstance();

    driveBaseLeftFrontMotor.reset(new Talon(LEFT_FRONT_MOTOR_CHANNEL));
    lw->AddActuator("Drive Base", "Left Front Motor", std::static_pointer_cast<Talon>(driveBaseLeftFrontMotor));

    driveBaseLeftRearMotor.reset(new Talon(LEFT_REAR_MOTOR_CHANNEL));
    lw->AddActuator("Drive Base", "Left Rear Motor", std::static_pointer_cast<Talon>(driveBaseLeftRearMotor));
    
    driveBaseRightFrontMotor.reset(new Talon(RIGHT_FRONT_MOTOR_CHANNEL));
    lw->AddActuator("Drive Base", "Right Front Motor", std::static_pointer_cast<Talon>(driveBaseRightFrontMotor));

    driveBaseRightRearMotor.reset(new Talon(RIGHT_REAR_MOTOR_CHANNEL));
    lw->AddActuator("Drive Base", "Right Rear Motor", std::static_pointer_cast<Talon>(driveBaseRightRearMotor));

    driverStick.reset(new Joystick(DRIVER_JOYSTICK_PORT));
    auxiliaryStick.reset(new Joystick(AUXILIARY_JOYSTICK_PORT));

#ifdef USE_FRC_DRIVE_CODE
    driveBaseRobotDrive21.reset(new RobotDrive(driveBaseLeftFrontMotor, driveBaseLeftRearMotor,
    										   driveBaseRightFrontMotor, driveBaseRightRearMotor));
    
    driveBaseRobotDrive21->SetSafetyEnabled(true);
        driveBaseRobotDrive21->SetExpiration(0.1);
        driveBaseRobotDrive21->SetSensitivity(0.5);
        driveBaseRobotDrive21->SetMaxOutput(1.0);
#endif
}
