// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTONOMOUS_COMMAND_H
#define AUTONOMOUS_COMMAND_H

#define SIMPLE_AUTO_MODE

#include "CloneableCommand.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutonomousCommand: public Command {
public:
    enum FieldPosition {
        ePositionNull = 0,
        ePosition1 = 1,
        ePosition2 = 2,
        ePosition3 = 3,
        ePosition4 = 4,
        ePosition5 = 5
    };
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    AutonomousCommand(int TargetPosition);
    AutonomousCommand(FieldPosition TargetPosition);

    virtual void Initialize();
    virtual void Execute();
    virtual bool IsFinished();
    virtual void End();
    virtual void Interrupted();

private:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    FieldPosition m_TargetPosition;
    bool isEndstep;
    int autoStage;
    int endstepTimer;

    bool Auto1 ();
    bool Auto2 ();
    bool Auto3 ();
    bool Auto4 ();
    bool Auto5 ();

    void StopOperations();
};

#endif
