// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OneManIntakeArm.h"

#include <Commands/Subsystem.h>
#include "../Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

OneManIntakeArm::OneManIntakeArm() :
		Command() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intakeArm.get());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void OneManIntakeArm::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void OneManIntakeArm::Execute() {
	if (Robot::oi->getPilotStick()->GetRawButton(1)
			&& !Robot::oi->getPilotStick()->GetRawButton(2)) {
		Robot::intakeArm->SetArmDirection(IntakeArm::kRising);
	} else if (!Robot::oi->getPilotStick()->GetRawButton(1)
			&& Robot::oi->getPilotStick()->GetRawButton(2)) {
		Robot::intakeArm->SetArmDirection(IntakeArm::kFalling);
	} else {
		Robot::intakeArm->SetArmDirection(IntakeArm::kOff);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool OneManIntakeArm::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void OneManIntakeArm::End() {
	Robot::intakeArm->StopArm();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void OneManIntakeArm::Interrupted() {
	Robot::intakeArm->StopArm();
}
