// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIGHTING_H
#define LIGHTING_H
// #include "Commands/Subsystem.h"
#include <WPILib.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class Lighting: public Subsystem {
public:
	Lighting();
	void InitDefaultCommand();

	enum Alliance {
		eRed = 0, eBlue = 1, eDemo = 2
	};
	void setAlliance(Alliance alliance);

	enum Mode {
		eIdle = 0, eTeleOp = 1, eAuto = 2, eError = 3
	};
	void setMode(Mode mode);

protected:
	void sendLightingCommand();

private:
	std::shared_ptr<SerialPort> serialPort_;
	Alliance alliance_;
	Mode mode_;
};

#endif
