// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include <WPILib.h>


class OI {
private:
	std::shared_ptr<Joystick> driveStick;		//Primary controller, controls drive base
	std::shared_ptr<Joystick> auxStick;		//Second controller, controls all but drive base

public:
	OI();

	//Returns a pointer to the primary control stick
	std::shared_ptr<Joystick> getDriveStick() {
		return driveStick;
	}

	//Returns a pointer to the secondary control stick
	std::shared_ptr<Joystick> getAuxStick() {
		return auxStick;
	}
};

#endif
