// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "Switchboard.h"
#include "WPILib.h"
#include "ThirdParty/NavX/include/AHRS.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> driveBaseLeftFront;
	static std::shared_ptr<SpeedController> driveBaseRightFront;
	static std::shared_ptr<SpeedController> driveBaseLeftRear;
	static std::shared_ptr<SpeedController> driveBaseRightRear;
	static std::shared_ptr<AHRS> driveBaseNavX;
	static std::shared_ptr<SpeedController> shooterArmLeftArm;
	static std::shared_ptr<SpeedController> shooterArmRightArm;
	static std::shared_ptr<Encoder> shooterArmLeftArmEncoder;
	static std::shared_ptr<Encoder> shooterArmRightArmEncoder;
	static std::shared_ptr<SpeedController> shooterLeftWheel;
	static std::shared_ptr<SpeedController> shooterRightWheel;
	static std::shared_ptr<DoubleSolenoid> shooterIntakePiston;
	static std::shared_ptr<SerialPort> lightingSerialPort;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
