// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MOVEFORTIME_H
#define MOVEFORTIME_H

#include <WPILib.h>


// CODE_REVIEW(mjh): Document what this class actually does.
// CODE_REVIEW(mjh): Consider rewriting this class to be derived from the
// frc::TimedCommand class, rather than re-implementing its functionality.
class MoveForTime: public Command {
public:
	MoveForTime(double seconds, double power);

	virtual void Initialize() override;
	virtual void Execute() override;
	virtual bool IsFinished() override;
	virtual void End() override;
	virtual void Interrupted() override;

private:
    double m_seconds;
    double m_power;
    int counter;
};

#endif
