// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Intake.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Intake::Intake() :
		Subsystem("Intake") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftIntakeWheel = RobotMap::intakeLeftIntakeWheel;
	rightIntakeWheel = RobotMap::intakeRightIntakeWheel;
	pusher = RobotMap::intakePusher;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	rightIntakeWheel->SetInverted(true);
}

void Intake::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	// SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Intake::SetPower(Direction whichDirection) {
	switch (whichDirection) {
	case kIntake:
		leftIntakeWheel->Set(.25);
		rightIntakeWheel->Set(.25);
		pusher->Set(Relay::kReverse);
		break;
	case kOutput:
		leftIntakeWheel->Set(-.5);
		rightIntakeWheel->Set(-.5);
		pusher->Set(Relay::kOn);
		break;
	default:
		leftIntakeWheel->Set(0);
		rightIntakeWheel->Set(0);
		pusher->Set(Relay::kOff);
		break;
	}
}

void Intake::StopIntake(){
	leftIntakeWheel->Set(0);
	rightIntakeWheel->Set(0);
	pusher->Set(Relay::kOff);
}
