// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef _ROBOT_H
#define _ROBOT_H

#include <WPILib.h>
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

#include "Commands/CommandGroups/TeleopCommandGroup.h"
#include "Commands/Lights/AutomaticLighting.h"
#include "Commands/CommandGroups/Autonomous.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Subsystems/ClimberSystem.h"
#include "Subsystems/DriveBase.h"
#include "Subsystems/GearSystem.h"
#include "Subsystems/ArduinoController.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot: public IterativeRobot {
public:
	static std::shared_ptr<CommandGroup> autonomousCommand;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<DriveBase> driveBase;
	static std::shared_ptr<GearSystem> gearSystem;
	static std::shared_ptr<ClimberSystem> climberSystem;
	static std::shared_ptr<ArduinoController> arduinoController;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<CommandGroup> teleopCommand;
	static std::shared_ptr<Command>	lightingCommand;

	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();
};
#endif
