// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PNEUMATIC_MOVE_H
#define PNEUMATIC_MOVE_H


#include <WPILib.h>

/**
 *
 *
 * @author ExampleAuthor
 */
// FINDME(mjh): This class is not implemented correctly, and should either be
// fixed or removed.  Among other issues, the "rampDouble" solenoid object
// (and its attempted use in the .cpp) have been commented-out, since it's not
// wired in correctly, and could conflict with other device definitions.
class PneumaticMove: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	PneumaticMove();

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;
private:
//	frc::DoubleSolenoid rampDouble {1,2};

};

#endif
