#pragma once
#include "vision/VisionPipeline.h"

#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* MultipleOutputs class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class MultipleOutputs : public frc::VisionPipeline {
	private:
		cv::Mat cvResizeOutput;
		cv::Mat hsvThreshold0Output;
		cv::Mat cvErode0Output;
		std::vector<std::vector<cv::Point> > findContours0Output;
		std::vector<std::vector<cv::Point> > filterContours0Output;
		cv::Mat hsvThreshold1Output;
		cv::Mat cvErode1Output;
		std::vector<std::vector<cv::Point> > findContours1Output;
		std::vector<std::vector<cv::Point> > filterContours1Output;
		void cvResize(cv::Mat &, cv::Size &, double , double , int , cv::Mat &);
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void cvErode(cv::Mat &, cv::Mat &, cv::Point &, double , int , cv::Scalar &, cv::Mat &);
		void findContours(cv::Mat &, bool , std::vector<std::vector<cv::Point> > &);
		void filterContours(std::vector<std::vector<cv::Point> > &, double , double , double , double , double , double , double [], double , double , double , double , std::vector<std::vector<cv::Point> > &);

	public:
		MultipleOutputs();
		void Process(cv::Mat& source0) override;
		cv::Mat* GetCvResizeOutput();
		cv::Mat* GetHsvThreshold0Output();
		cv::Mat* GetCvErode0Output();
		std::vector<std::vector<cv::Point> >* GetFindContours0Output();
		std::vector<std::vector<cv::Point> >* GetFilterContours0Output();
		cv::Mat* GetHsvThreshold1Output();
		cv::Mat* GetCvErode1Output();
		std::vector<std::vector<cv::Point> >* GetFindContours1Output();
		std::vector<std::vector<cv::Point> >* GetFilterContours1Output();
};


} // end namespace grip


