// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "IntakeArm.h"
#include "../RobotMap.h"

IntakeArm::IntakeArm() : Subsystem("IntakeArm") {
    leftArm = RobotMap::intakeArmLeftArm;
    rightArm = RobotMap::intakeArmRightArm;
    leftEncoder = RobotMap::intakeArmLeftEncoder;
    rightEncoder = RobotMap::intakeArmRightEncoder;
}

void IntakeArm::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
}

