// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

#include <SmartDashboard/SmartDashboard.h>

#include "Commands/MoveInSquare.h"
#include "Commands/Arman.h"
#include "Commands/MoveForTime.h"
#include "Commands/PointTurnForAngle.h"
#include "Commands/GearTeleop.h"
#include "Commands/IntakeAuto.h"
#include "Commands/MoveForDistance.h"
#include "Commands/ActuatorAuto.h"
#include "Commands/outputAuto.h"
#include "RobotVariables.h"
#include "Commands/tankDrive.h"
#include "Commands/AuxiliaryCommands.h"
#include "Commands/ReverseIntakeAuto.h"
#include "Commands/OutputAuto.h"
#include "Commands/ClimberAuto.h"

#define simpleInterface
OI::OI() {
    // Process operator interface input here.
    auxStick.reset(new Joystick(AuxStickPort));
    driveStick.reset(new Joystick(DriverStickPort));
    
#ifndef simpleInterface
    //Smart Dashboard Buttons
    SmartDashboard::PutData("Servo", new GearTeleop());
    SmartDashboard::PutData("Intake Auto", new IntakeAuto(.50));
    SmartDashboard::PutData("Outtake Auto", new OutputAuto(.5));
    SmartDashboard::PutData("Linear Actuator in", new ActuatorAuto (false));
    SmartDashboard::PutData("Linear Actuator Out", new ActuatorAuto (true));
#else
    SmartDashboard::PutData("Tank Drive", new TankDrive());
    SmartDashboard::PutData("Intake Backwash", new ReverseIntakeAuto(-.5));
    SmartDashboard::PutData("Auxillary Commands", new AuxiliaryCommands());

    SmartDashboard::PutData("Climber Forwards", new ClimberAuto(.5));
    SmartDashboard::PutData("Climber Backwards", new ClimberAuto(-.5));
    SmartDashboard::PutData("Climber Stop", new ClimberAuto(0));

#endif
}

std::shared_ptr<Joystick> OI::getDriveStick() {
   return driveStick;
}

std::shared_ptr<Joystick> OI::getAuxStick() {
   return auxStick;
}
